server:
  port: 7777
spring:
  datasource:
    username: root
    password: 550098879
    url: jdbc:mysql://localhost:3306/eshop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource                #druid连接池


# 2.3.0版本的SpringBoot暂时还不支持thymeleaf的解析
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html