server:
  port: 7777
spring:
  datasource:
    username: root
    password: 550098879
#    远程数据库ip地址
    url: jdbc:mysql://*****:3306/eshop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource                #druid连接池


# 2.3.0版本的SpringBoot暂时还不支持thymeleaf的解析
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#mybatis-plus:    #打印SQL语句
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-enums-package: org.zyx.enums
  global-config:
    db-config:
      logic-not-delete-value: 0   #0表示存在
      logic-delete-value: 1       #1表示删除
